stages:
  - test
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image:dind

test calc:
  stage: test
  tags:
    - calc
  script:
    - ./gradlew check

build calc:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - calc
  script:
    - ./gradlew assemble

deploy calc:
  image: docker:latest
  stage: deploy
  tags:
    - calc
  script:
    - docker build -t htoots/unity --build-arg JAR_FILE=build/libs/*.jar .
    - docker run htoots/unity

