stages:
  - test
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test calc:
  stage: test
  tags:
    - calc
  script:
    - ./gradlew check

build calc:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - calc
  script:
    - ./gradlew assemble

deploy calc:
  stage: deploy
  tags:
    - calc
  script:
    - mkdir -p ~/api-deployment # mkdir make folder api-deployment ~/ is under current user directory so for gitlab it would be /home/gitlab/api-deployment
    - rm -rf ~/api-deployment/* # rm remove -rf is recursive files from api-deployment
    - cp -r build/libs/. ~/api-deployment # cp - copy build/libs is where
    - sudo service unity restart
