stages:
  - test
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test calc:
  stage: test
  tags:
    - calc
  script:
    - ./gradlew check

build calc:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - calc
  script:
    - ./gradlew assemble

deploy calc:
  stage: deploy
  tags:
    - calc
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
    - sudo service calculator restart

